// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTTDay09CodeFirst.Models;

#nullable disable

namespace NTTDay09CodeFirst.Migrations
{
    [DbContext(typeof(nttContext))]
    [Migration("20251018125031_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NTTDay09CodeFirst.Models.ntt_LoaiSanPham", b =>
                {
                    b.Property<long>("nttId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nttId"));

                    b.Property<string>("nttMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("nttTenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("nttTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("nttId");

                    b.ToTable("ntt_LoaiSanPham");
                });

            modelBuilder.Entity("NTTDay09CodeFirst.Models.ntt_SanPham", b =>
                {
                    b.Property<long>("nttId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nttId"));

                    b.Property<decimal>("nttDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nttHinhAnh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("nttLoaiSPId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("nttMaSP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("nttSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("nttTenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("nttId");

                    b.HasIndex("nttLoaiSPId");

                    b.ToTable("ntt_SanPham");
                });

            modelBuilder.Entity("NTTDay09CodeFirst.Models.ntt_SanPham", b =>
                {
                    b.HasOne("NTTDay09CodeFirst.Models.ntt_LoaiSanPham", "nttLoai_SP")
                        .WithMany("nttSanPhams")
                        .HasForeignKey("nttLoaiSPId")
                        .HasPrincipalKey("nttMaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nttLoai_SP");
                });

            modelBuilder.Entity("NTTDay09CodeFirst.Models.ntt_LoaiSanPham", b =>
                {
                    b.Navigation("nttSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
